name: Build Qt App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.1"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          cache: true

      - name: Configure
        run: cmake -S . -B out/build/x64-debug

      - name: Build
        run: cmake --build out/build/x64-debug --config Debug

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Configured-windows-debug
          path: out/build/x64-debug/Configured.exe
